services:
  - type: web
    name: havix-api
    env: node
    plan: free
    buildCommand: |
      npx --yes extract-zip havix-erp.zip $PWD
      cd apps/backend
      npm install
      npx prisma generate
    startCommand: |
      cd apps/backend
      npx prisma db push
      npm run start
    envVars:
      - key: DATABASE_URL
        sync: false

  - type: web
    name: havix-web
    env: node
    plan: free
    buildCommand: |
      npx --yes extract-zip havix-erp.zip $PWD
      cd apps/web
      npm install
      npm run build
    startCommand: |
      cd apps/web
      npm run start
